### ISSUE TITLE
requirements.txt not used?

### ISSUE THREAD

**Issue by heilmic** [Seji64/spoonie#4]
I think my Portainer Stack is using the wrong version of tonie_api and not your fork. 

If I start the container and try to install the tonie-api by hand, I get the error that no git is installed. 

I don't know where to search my error. 

Can you please help me, to get it working again?

checking tonie_api installed (in the container)
```
255f69fd2d0c:/app# pip show tonie_api
Name: tonie-api
Version: 0.1.1
Summary: Python library to access the REST API of the toniecloud. NOT associated with Boxine (tonies.de) in any way.
Home-page: https://github.com/Wilhelmsson177/tonie-api
Author: Willi Meierhof
Author-email: willi@meierhof.dev
License: MIT
Location: /usr/local/lib/python3.12/site-packages
Requires: pydantic, requests-oauthlib
Required-by: 
```

try to install your fork in the created container (probably not possible this way)
```
255f69fd2d0c:/app# pip install 'tonie_api @ git+https://github.com/Seji64/tonie-api'
Collecting tonie_api@ git+https://github.com/Seji64/tonie-api
  Cloning https://github.com/Seji64/tonie-api to /tmp/pip-install-id2n2m3e/tonie-api_88d7c1eec0fc4e37b649b040679b3623
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

```

Stack Settings Portainer
```
name: spoonie-feuerwehr-tonie
services:
    spoonie:
        restart: unless-stopped
        volumes:
            - /opt/spoonie:/app/data
        environment:
            - SPOTIFY_USERNAME=xxxx@gmail.com
            - SPOTIFY_PASSWORD=password
            - TONIE_USERNAME=xxxxx@gmail.com
            - TONIE_PASSWORD=password
            - TONIE_HOUSEHOLD=Mein Haushalt
            - CREATIVE_TONIE=Feuerwehr-Tonie
            - PLAYLIST=https://open.spotify.com/playlist/aaaaa&pt=bbbb
        container_name: sync-feuerwehr-tonie
        image: ghcr.io/seji64/spoonie:latest
```
